// sdk/apimanagement/api-management-custom-widgets-scaffolder/bin/templates/react/src/editor/index.tsx
import {useEditorValues, useOnChange} from "../hooks"
import {Values, valuesDefault} from "../values"

function InputField({valueKey, title}: {valueKey: keyof Values, title?: string}) {
  const editorValues = useEditorValues()
  const onChange = useOnChange()

  return (
    <div className="form-group">
      <label className="form-label" htmlFor={valueKey}>
        {title ?? valueKey}
      </label>
      <div className="input-group">
        <input
          className="form-control"
          type="text"
          placeholder={valuesDefault[valueKey]}
          defaultValue={editorValues[valueKey]}
          onInput={e => {
            const target = e.target as HTMLInputElement
            onChange({[valueKey]: target.value})
          }}
        />
      </div>
    </div>
  )
}

const Editor = () => (
  <fieldset className="form">
    <div className="form-group">
      <InputField valueKey="label1" title="Label 1" />
      <InputField valueKey="label2" title="Label 2" />
      <InputField valueKey="placeholder" title="Placeholder" />
      <InputField valueKey="actionUrl" title="Action URL" />
    </div>
  </fieldset>
)

export default Editor

// sdk/apimanagement/api-management-custom-widgets-scaffolder/src/templates/vue/src/components/editor/index.vue
<style lang="scss" src="../../styles/editor.scss"></style>

<template>
  <div class="form">
    <div class="form-group">
      <label for="actionUrl" class="form-label">Label 1</label>
      <input id="actionUrl" type="text" class="form-control" v-model="label1" />
    </div>
    <div class="form-group">
      <label for="actionUrl" class="form-label">Label 2</label>
      <input id="actionUrl" type="text" class="form-control" v-model="label2" />
    </div>
    <div class="form-group">
      <label for="actionUrl" class="form-label">Placeholder</label>
      <input id="actionUrl" type="text" class="form-control" v-model="placeholder" />
    </div>
    <div class="form-group">
      <label for="actionUrl" class="form-label">Action URL</label>
      <input id="actionUrl" type="text" class="form-control" v-model="actionUrl" />
    </div>
  </div>
</template>

<script lang="ts">
import {buildOnChange, getEditorData} from "@azure/api-management-custom-widgets-tools"
import {valuesDefault} from "../../values"

export default {
  data: () => ({...valuesDefault}),

  async mounted(): Promise<void> {
    this.onChange = buildOnChange(valuesDefault)

    const editorData = getEditorData(valuesDefault)

    this.label1 = editorData.values.label1
    this.label2 = editorData.values.label2
    this.placeholder = editorData.values.placeholder
    this.actionUrl = editorData.values.actionUrl
  },

  watch: {
    label1(newValue: string): void {
      this.onChange({label1: newValue})
    },
    label2(newValue: string): void {
      this.onChange({label2: newValue})
    },
    placeholder(newValue: string): void {
      this.onChange({placeholder: newValue})
    },
    actionUrl(newValue: string): void {
      this.onChange({actionUrl: newValue})
    },
  },
}
</script>
